config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  namespace :api, defaults: {format: :json} do
    resources :events do 
      resources :comments
    end
    get '/users/:id' => 'users#show'
    post '/volunteers' => 'events#add_volunteer'
  end

  resources :users, only: [:create, :edit, :update]
  get '/signup' => 'users#new', as: :signup

  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: :logout

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base

	has_many :users, through: :events_users
	has_many :events_users
	belongs_to :creator, class_name: "User"
	
	has_many :comments, dependent: :destroy

	mount_uploader :image, AvatarUploader

	validates :title, presence: true
	validates :description, presence: true
	validates :location, presence: true
	validates :goal, presence: true
	validates :date, presence: true
	validates :short, presence: true, length: {maximum: 40}
	
	geocoded_by :location   # can also be an IP address
	after_validation :geocode          # auto-fetch coordinates
end

app/models/events_user.rb
class EventsUser < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :events, through: :events_users
	has_many :events_users
	# has_many :events, as: :creator
	
	has_many :comments, dependent: :destroy

	has_secure_password

	def created_events 
		Event.where(creator: self)
	end

	validates :username, presence: true, uniqueness: { case_sensitive: false }
	validates :name, presence: true, uniqueness: { case_sensitive: false }
	validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, uniqueness: {case_sensitive: false}, length: {maximum: 255}
	validates :password, length: {minimum: 6}
end

app/controllers/api/comments_controller.rb
module API
  class CommentsController < ApplicationController

    protect_from_forgery with: :null_session

    respond_to :html, :xml, :json

    def index
      respond_with Comment.all, default_serializer_options
    end

    def show
      respond_with Comment.find(params[:id])
    end

    def create
      comment = Comment.new(comment_params)

      # Get the default user_id
      user = User.find(params[:user_id])      
      comment.user = user         

      # Save method
      if comment.save
        render json: comment, status: 201
      else
        render json: {errors: comment.errors}, status: 422
      end
    end

    def update
      comment = Comment.find(params[:id])
      if Comment.update(comment_params)
        render json: comment,
        status: 200
      else
        render json: {errors: comment.errors}, status: 422
      end
    end

    def destroy
      comment = Comment.find(params[:id])
      comment.destroy
      head 204
    end

    private
    
      def comment_params
        params.require(:comment).permit(:body, :user_id, :event_id)
      end

  end
end

app/controllers/api/events_controller.rb
module API
	class EventsController < ApplicationController
		include EventsHelper
		
		protect_from_forgery with: :null_session

		respond_to :json, :html

		def index
			respond_with Event.all
		end

		def show
			respond_with Event.find(params[:id])
			event = Event.find(params[:id])
			address = event.location
			# binding.pry
			google_maps(address)
		end

		def create
			# user = User.find(params[:user_id])
			# event = user.events.create(event_params)
			event = Event.new(event_params)
			#user = User.find(params[:user_id])
			user = User.find(params[:user][:id])
			event.creator = user
			event.image = params[:file]

			if event.save
				render json: event, status: 201
			else
				render json: {errors: event.errors}, status: 422
			end
		end

		def update
			event = Event.find(params[:id])
			if event.update(event_params)
				render json: event, status: 200
			else
				render json: {errors: event.errors}, status: 422
			end
		end

		def destroy
			event = Event.find(params[:id])
			event.destroy
			head 204
		end

		def add_volunteer
			volunteer = EventsUser.new
			volunteer.user_id = params[:user_id]
			volunteer.event_id = params[:event_id]
			if volunteer.save
				render json: volunteer, status: 201
			else
				render json: {errors: volunteer.errors}, status: 422
			end
		end

		def add_comment
			comment = Comment.new
			comment.user_id = params[:user_id]
			comment.event_id = params[:event_id]
		end

		private

		def event_params
			params.require(:event).permit(:title, :description, :location, :goal, :date, :image, :hours, :short, :geocode, :user_id)
		end
	end
end

app/controllers/api/users_controller.rb
module API
	class UsersController < ApplicationController
	
		protect_from_forgery with: :null_session

		respond_to :json, :html

		def show
			@user = User.find(params[:id])
			respond_with @user
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def default_serializer_options
  	{ root: false }
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(username: params[:session][:username])
		if user && user.authenticate(params[:session][:password])
			log_in(user)
			redirect_to root_path
		else
			redirect_to login_path
		end
	end

	def destroy
		log_out if logged_in?
		redirect_to root_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def new
		@user = User.new
		if logged_in?
			redirect_to root_path
		end
	end

	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			redirect_to root_path
		else
			render :new
		end
	end

	def edit
		@user = current_user
	end

	def update
		@user = current_user
		if @user.update_attributes(user_params)
			redirect_to root_path
		else
			render :edit
		end
	end

	private

	def user_params
		params.require(:user).permit(:username, :name, :email, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper

	def google_maps(address)
		address = address.gsub " ","+"
		map_api = ENV['GOOGLE_MAPS']
		@map = "https://www.google.com/maps/embed/v1/place?key=#{map_api}&q=#{address}"
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		cookies[:id] = user.id
	end

	def current_user
		if cookies[:id]
			@current_user ||= User.find(cookies[:id])
		end
	end

	def logged_in?
	  	!current_user.nil?
	end

	def log_out    
	  	session.delete(:id)
	  	cookies.delete('id')
	  	@current_user = nil
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="ReachOutApp">
<head>
  <title>ReachOut</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <meta name="viewport" content="initial-scale=1.0,width=device-width,user-scalable=0" />
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Neucha|Anton|Pacifico|Rock+Salt' rel='stylesheet' type='text/css'>
</head>
<body>
<%= render 'shared/nav' %>
<!-- <iframe src="<%= @map %>"></iframe> -->
<%= yield %>

</body>
</html>

app/views/shared/_nav.html.erb
<% if logged_in? == false %>
	<header>
		<div id="nav-bar">
			<div>
				<h1 id="logo"><a href="/#/">ReachOut</a></h1>
			</div>
			<div id="sign-log">
				<div>
					<%= link_to "Sign Up", signup_path %>
				</div>
				<div>
					<%= link_to "Log In", login_path %>
				</div>
			</div>
		</div>
	</header>
<% end %>

<% if logged_in? %>
	<header>
		<div id="nav-bar">
				<div>
					<h1 id="logo"><a href="/#/">ReachOut</a></h1>
				</div>
				<div id="nav-first">
				<div>
					<a href="#/events">Events</a>
				</div>
				<div>
					<a href="#/events/new">Create an Event</a>
				</div>
			</div>
			<div id="drop-menu">
				<div class="dropdown">
				  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
				    Me
				    <span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
				    <li role="presentation"><a href="#/profile/<%= current_user.id %>">My Profile</a></li>
				    <li role="presentation"><%= link_to "Edit Account", edit_user_path(current_user) %></li>
				    <li role="presentation"><%= link_to "Log Out", logout_path, method: :delete %></li>
				  </ul>
				</div>
			</div>
		</div>
	</header>
<% end %>

app/views/static_pages/home.html.erb
<% if logged_in? %>
 <div ng-init="main.init(<%= current_user.id %>)"></div>
<% end %>
<div ng-view></div>

app/views/users/edit.html.erb
<h1>Edit my Account</h1>

<%= form_for @user do |f| %>
	
	<div>
		<%= f.text_field :username, placeholder: "Username" %>
	</div>
	<div>
		<%= f.text_field :name, placeholder: "Full Name" %>
	</div>
	<div>
		<%= f.text_field :email, placeholder: "Email" %>
	</div>
	<div>
		<%= f.password_field :password, placeholder: "Password" %>
	</div>
	<div>
		<%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
	</div>
	<%= f.submit "Update" %>

<% end %>

app/views/users/new.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<ul class="list-group">
		  <% @user.errors.full_messages.each do |msg| %>
		    <li class="list-group-item list-group-item-danger"><%= msg %></li>
		  <% end %>
		</ul>

		<h1 class="text-center">Sign Up</h1>

		<%= form_for @user do |f| %>
			
			<div class="form-group">
				<%= f.text_field :username, placeholder: "Username", class: "form-control"  %>
			</div>
			<div class="form-group">
				<%= f.text_field :name, placeholder: "Full Name", class: "form-control"  %>
			</div>
			<div class="form-group">
				<%= f.text_field :email, placeholder: "Email", class: "form-control"  %>
			</div>
			<div class="form-group">
				<%= f.password_field :password, placeholder: "Password", class: "form-control"  %>
			</div>
			<div class="form-group">
				<%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: "form-control"  %>
			</div>
			<%= f.submit "Sign Up", class: "btn btn-primary" %>

		<% end %>
	</div>
</div>